{% set name = "dash-bootstrap-components" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1804487a1a47290a3a3a74ff6fbbe54b5359096761e8fd6158dfa389f3492b6b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dash >=1.3.0

test:
  imports:
    - dash_bootstrap_components

about:
  home: https://dash-bootstrap-components.opensource.faculty.ai/
  license: MIT
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Bootstrap components for Plotly Dash'

  description: |
    Plotly Dash is great! However, creating the initial layout can create a lot of boilerplate.
    dash-bootstrap-components reduces this boilerplate by providing standard layouts and
    high-level components.

    dash-bootstrap-components provides Bootstrap components. It is built on top of reactstrap.
  doc_url: https://dash-bootstrap-components.opensource.faculty.ai/
  dev_url: https://github.com/facultyai/dash-bootstrap-components

extra:
  recipe-maintainers:
    - holtgrewe
    - pbugnion
    - tcbegley
