travis:
  secure:
    BINSTAR_TOKEN: an2cH2b8IjO0Npe0T3fXIwvCfS5Vsn9ElKzRey9Fw7b7dX7zreL7wVD6LJmNrfnm/Bw4udqwFDnv0CbM2n/oP9Ufa9IQSU+ab37nmlEDgO0nnuUSJ8dxbF0BUiFgS14kdyOPzUV0/U3w2WJJyyktTE+IuDVhEoeARYOqS9BfTdoIGD0lsBqENEOtn7/rKZoECu8nALgzGG5Y5T3UGhHPomt//kKSwriUeZ4PE12LhOf1Jd/bvwmY3Mon6dF4I2fZLQjogVT46/HO7VVkqnb6kZ1FxiEgrfnBXe7zluanBLg0hO5FGG2qVl2fHbtzTqbDWKihTVN9fAjq68+ULIofstf419t5KFH2w5EO/fqVir6JOz9qJBtQ2997QIwdTUDHxaWHXqJgJxfjAuS+9xD5qbIZL7wmDQ957SpdVMC50C6UdMbsb8n/ySLSPjUVVJ++PK6UtMTo9JDXZv69pkq99J3dQq6/SWkQwwIfncRJHDUYDzT2CNf1KcMDRk2ZdNJMyL22PF2Ficz84y2USJs/0JVMDbuS/QRqZg1RuvdUgkgc7ddNSYcRZAsh4dJ53ooLkmcleQkDthBdVWBTiSNC7+hjZV9Ib65YbvJlkjRDj3Wjoykx3rDkzVUd5MfPGRZznJ7Te3csV5p48XOlejgYfnhflMbPJ2OxbchUvPJ8CFg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
